### ISSUE TITLE
Move all issues in this repository

### ISSUE THREAD

**Issue by Neustradamus** [jitsi/otr4j#7] opened 2020-07-28 05:25 UTC
@ibauersachs, I think that you have not read ALL steps, please read a new time.

Please:
- Create a new personal repository: "ibauersachs/example"
- Unarchive ibauersachs/otr4j
- Transfer all opened and closed issues from ibauersachs/otr4j into your new personal temp repository
- After all opened and closed issue transfers, archive a new time ibauersachs/otr4j
- Move your "ibauersachs/example" temp repository into jitsi organization
- Transfer all opened and closed issues from the temp repository into jitsi/otr4j
- After all opened and closed issue transfers, remove your "ibauersachs/example" temp repository

Thanks to @cobratbq about the job since several years!

Thanks in advance.

Neustradamus, the man who has done the official comeback of OTR4J, a dead project since Jun 2, 2016.

Linked to:
- https://github.com/jitsi/otr4j/issues/6

**Comment by Neustradamus** [comment] 2020-07-29 21:58
Dear @jitsi team, @ibauersachs: I have transferred all issues (closed and opened) from "otr4j-temp/otr4j" into a new repository with success.

Steps that I have done:
1/ I have created a new repository "otr4j-issues" into "otr4j-temp" organization
2/ I have transferred all issues from "otr4j-temp/otr4j" into "otr4j-temp/otr4j-issues"
3/ I have transferred "otr4j-temp/otr4j-issues" repository to "otr4j/otr4j-issues"

You can see:
- https://github.com/otr4j/otr4j-issues

Steps to do:
- Transfer this repository in your personal account "ibauersachs"
- Unarchive "ibauersachs/otr4j"
- Transfer all issues from "ibauersachs/otr4j" into "ibauersachs/otr4j-issues"
- Transfer "ibauersachs/otr4j-issues" to "jitsi/otr4j-issues"
- Transfer all issues from "jitsi/otr4j-issues" into "jitsi/otr4j"
- Remove "jitsi/otr4j-issues"
- Remove "ibauersachs/otr4j" (please look other branches before)

After it, the World will be perfect and better with jitsi/otr4j.

cc @cobratbq.

PS: I can do it freely, if I have all rights.

**Comment by ibauersachs** [comment] 2020-08-05 15:15
Duplicate of #6. Not worth the effort.

**Closed as completed by ibauersachs** 2020-08-05 15:15 UTC
